[package]
name = "framevm_cargo"
version = "0.1.0"
edition = "2024"

[dependencies]
getopts = "0.2"
clap = "2.33"
walkdir = "2"
regex = "1"
itertools = "0.10"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
shell-words = "1.0"

[lints]
workspace = true
