[package]
name = "aster-framevm"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "framevm"
path = "src/main.rs"

[dependencies]
ostd = { package = "ostd" , path = "../../../ostd" }
framevisor = { package = "aster-framevisor", path = "../framevisor" }
align_ext = { path = "../../../ostd/libs/align_ext" }

[lints]
workspace = true